"""Taiwan readings: words Taiwan reads differently from pypinyin (mainland)."""

from __future__ import annotations

import logging
from pathlib import Path

from pypinyin import Style, lazy_pinyin

_LOGGER = logging.getLogger(__name__)

_TABLE_PATH = Path(__file__).with_name("taiwan_readings.tsv")


class TaiwanReadings:
    """Taiwan pinyin for words whose initial or final differs from pypinyin's.

    pypinyin reads 垃圾 lā jī; Taiwan says lè sè, which STT spells 樂瑟.
    Listed words take their Taiwan reading; the rest of the text keeps
    pypinyin's. The table is generated by
    ``scripts/mandarin/taiwan_readings.py``.
    """

    def __init__(self, table: dict[str, tuple[str, ...]]) -> None:
        """Initialize with a word -> TONE3 syllables table."""
        self._table = table
        self._max_len_by_first: dict[str, int] = {}
        for word in table:
            first = word[0]
            self._max_len_by_first[first] = max(
                self._max_len_by_first.get(first, 0), len(word)
            )

    @classmethod
    def load(cls, path: Path = _TABLE_PATH) -> TaiwanReadings:
        """Read the shipped table. Blocking file I/O."""
        table: dict[str, tuple[str, ...]] = {}
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            word, reading = line.split("\t")
            table[word] = tuple(reading.split())
        _LOGGER.debug("Loaded %d Taiwan readings from %s", len(table), path.name)
        return cls(table)

    def pinyin(self, text: str) -> list[str] | None:
        """TONE3 syllables of text with Taiwan readings applied.

        Returns:
            The syllables, or None when no listed word occurs in text.
        """
        result: list[str] = []
        pending_start = 0
        matched = False
        i = 0
        while i < len(text):
            longest = self._max_len_by_first.get(text[i], 0)
            for end in range(min(len(text), i + longest), i + 1, -1):
                reading = self._table.get(text[i:end])
                if reading is not None:
                    if pending_start < i:
                        result.extend(
                            lazy_pinyin(text[pending_start:i], style=Style.TONE3)
                        )
                    result.extend(reading)
                    matched = True
                    i = pending_start = end
                    break
            else:
                i += 1
        if not matched:
            return None
        if pending_start < len(text):
            result.extend(lazy_pinyin(text[pending_start:], style=Style.TONE3))
        return result


_shared: TaiwanReadings | None = None


def get_taiwan_readings() -> TaiwanReadings:
    """Get the shared Taiwan readings, loading them on first use.

    Must be called from an executor thread on first use (blocking file I/O);
    ``MandarinModule.preload`` does that at integration setup.
    """
    global _shared  # noqa: PLW0603 - process-wide immutable cache
    if _shared is None:
        _shared = TaiwanReadings.load()
    return _shared
